nombre=input("Ingresar el Nombre completo: ")
edad=int(input("Ingresar la Edad: "))
estatura=float(input("Ingresar la Estatura: "))
peso=float(input("Ingresar el Peso: "))
direccion=input("Ingresar la Direccion: ")
telefono=input("Ingresar el Telefono: ")
print('La información ingresada es la siguiente:')
print('Nombre completo: ',nombre)
print(f'Edad: ',edad)
print(f'Estatura: {estatura} cm')
print(f'Peso: {peso} Kg')
print('Dirección: ',direccion)
print('Número de teléfono: ',telefono)